# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update Search Index

on:
  workflow_dispatch:
  issues:
    types: [opened, edited, deleted, closed]

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: hmu332233/issues-search
          path: issues-search
      - name: Update Search Index
        uses: ./issues-search/.github/actions/update-search-index
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALGOLIA_ID: ${{ secrets.ALGOLIA_ID }}
          ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
          ALGOLIA_INDEX: ${{ secrets.ALGOLIA_INDEX }}
